### ISSUE TITLE
Smoothing out animation for flips

### ISSUE THREAD

**Issue by cwhunt** [helbling/passist#18]
Hi! First off I'd like to say thanks for an awesome program! I've been trying to find a more modern simulator (compared to JoePass or Jongl) to use to document the club passing patterns my local juggling club often uses. I've worked out a number of patterns and I've found that the animation for flips (also called vamps or straight singles - a single throw to the same hand) has a bit of a hitch in it. I may try to see if there's anything I can do to smooth it out but I'm including the simplest pattern with a flip as an example in case you are able to take a look. It's possible I'm not doing something right. In my club we call this "4-count fls" where fls stands for "flip last self". In words it's "pass self self flip" and the result is alternating right and left passes. I'm attaching the JIF file for the pattern but had to make it a Markdown file since you can't upload files with a .jif extension. I'm also attaching a movie of the result.

[2J_6C_4-count_fls_generated.md](https://github.com/helbling/passist/files/8312566/2J_6C_4-count_fls_generated.md)

https://user-images.githubusercontent.com/2301586/159194392-f4571f39-34e7-4a1c-bbce-ac3b1ba8464d.mp4

**Comment by cwhunt** [comment]
If it helps, the causal diagram is:

![two_6_4count_fls](https://user-images.githubusercontent.com/2301586/159194717-704c65f5-1732-41da-9b69-522eae3e2de6.png)

**Comment by helbling** [comment]
Thanks for the report.

First a quick not about the JIF format:
Please be aware, that this ist still under development. Until we have fully specified that, it could change unexpectedly.
See https://github.com/helbling/jif for the current status and a link to the mailing list.
I'm currently playing around with different drafts for JIF in passist to figure out how good they work in practice.
The `/jif` page is currently just a unofficial playground to see how the current draft behaves.

That beeing said, I really like that you are interested in passist, are playing around with it and even submit pull requests and issues. Thank you!

I think the issue with your example ist this:
The way you specified it, the second self is being thrown before it lands in the hand. Look these two throws of prop 4:
```
    {
      "time": 2,
      "duration": 3,
      "from": 0,
      "to": 2,
      "label": "3",
      "prop": 4
    },
[..]
    {
      "time": 4,
      "duration": 3,
      "from": 2,
      "to": 1,
      "label": "3",
      "prop": 4
    },

```
The self lands on time 5, however, the pass afterwards already goes away at time 4 causing the teleportation visible in the animation. 


For reference, here is the corresponding JIF as txt file as well (md looked a bit weird in my browser):
[issue18.jif.txt](https://github.com/helbling/passist/files/8314106/issue18.jif.txt)

**Comment by cwhunt** [comment]
Thanks for the quick response and explanation! The mailing list looks like it has a lot of good information and I'll read through the old posts. I think I fixed my JIF file and the animation looks good.

[2J_6C_4-count_fls_generated_adjusted_duration.jif.txt](https://github.com/helbling/passist/files/8319193/2J_6C_4-count_fls_generated_adjusted_duration.jif.txt)

https://user-images.githubusercontent.com/2301586/159362824-072b25bf-acec-4d1c-b292-3042c022c4b9.mp4

**Comment by cwhunt** [comment]
Oops, while I was working out the pattern for diagonal passes I noticed that my sitewap math didn't work out for this one so I fixed it. The result is:

https://user-images.githubusercontent.com/2301586/159539940-c9d8ff38-fb9b-4b7a-9000-f3d25832b762.mp4

This video better shows the actual timing (you throw the duration 2 throw slower and the duration 4 throw faster):

https://user-images.githubusercontent.com/2301586/159540076-5f893d42-055e-4c68-9114-9826a4e3a743.mp4

The corrected JIF file is:

[2J_6C_4-count_fls_generated_corrected_duration.jif.txt](https://github.com/helbling/passist/files/8326590/2J_6C_4-count_fls_generated_corrected_duration.jif.txt)

**Comment by cwhunt** [comment]
I'm tacking on a few more JIF files and a few more videos to refer to in a discussion on the JIF mailing list.

These first two videos show 4-count with diagonal passes (diagonal pass, self, self, self).

[2J_6C_4-count_diagonal_pass_unadjusted_timeStretchFactor.jif.txt](https://github.com/helbling/passist/files/8346659/2J_6C_4-count_diagonal_pass_unadjusted_timeStretchFactor.jif.txt)

https://user-images.githubusercontent.com/2301586/160036995-d48810b5-8048-4ae1-a8d9-43f3358c242e.mp4

[2J_6C_4-count_diagonal_pass.jif.txt](https://github.com/helbling/passist/files/8346660/2J_6C_4-count_diagonal_pass.jif.txt)

https://user-images.githubusercontent.com/2301586/160037047-224a4255-6ed4-4674-8d31-1f5b724e3d65.mp4

These last two show one person doing 4-count fls (pass, self, self, flip) and one person doing 4-count with diagonal passes (diagonal pass, self, self, self).

[2J_6C_4-count_fls_diagonal_unadjusted_timeStretchFactor.jif.txt](https://github.com/helbling/passist/files/8346657/2J_6C_4-count_fls_diagonal_unadjusted_timeStretchFactor.jif.txt)

https://user-images.githubusercontent.com/2301586/160037217-47ef56b6-e410-45e0-84cb-0ac408b67eab.mp4

[2J_6C_4-count_fls_diagonal.jif.txt](https://github.com/helbling/passist/files/8346658/2J_6C_4-count_fls_diagonal.jif.txt)

https://user-images.githubusercontent.com/2301586/160037229-6186030a-60b6-4a65-a3f1-e95ecb0871f4.mp4

For the second video in each pair I set an individual timeStretchFactor and used it in this way in [animation.js](https://github.com/helbling/passist/blob/main/src/lib/animation.mjs):

![throwTimeStretchFactor](https://user-images.githubusercontent.com/2301586/160037391-a2c9667f-7293-4c2d-8749-0ccf024b3e3c.png)
